name: familytrusts
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  firebase_analytics: ^10.1.0
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1

  flutter_facebook_auth: ^5.0.7
  flutter_localizations:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.7

  google_sign_in: ^5.4.2

  package_info: ^2.0.2

  sentry_flutter: ^6.18.1
  # device information

  connectivity: ^3.0.6
  device_info: ^2.0.2
  # system_info: ^1.0.1

  quiver: ^3.1.0
  path: ^1.8.1

  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  firebase_messaging: ^14.2.1
  overlay_support: ^2.1.0

  cached_network_image: ^3.2.3
  image_picker: ^0.8.6
  intl: ^0.17.0

  logging: ^1.1.0

  bloc: ^8.1.0
  flutter_form_bloc: ^0.30.1
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.5
  rxdart: ^0.27.7
  font_awesome_flutter: ^10.3.0

  enum_to_string: ^2.0.1
  badges: ^2.0.3
  freezed_annotation:
  dartz: ^0.10.1
  injectable: ^2.1.0
  get_it: ^7.2.0
  uuid: ^3.0.7
  auto_route: ^5.0.4
  another_flushbar: ^1.12.29
  json_annotation: ^4.7.0
  http: ^0.13.5

  meta: ^1.8.0

  stream_transform: ^2.1.0

  google_maps_place_picker_mb: ^3.0.0
  google_maps_flutter: ^2.2.3
  google_geocoding: ^0.2.0

  #geoflutterfire2: 2.3.14
  geolocator: ^9.0.2
  easy_localization: ^3.0.1
  # easy_localization_loader: ^1.0.0
  # slide_to_act: ^2.0.1
  # diacritic: ^0.1.1
  carousel_slider: ^4.2.1

  date_time_picker: ^2.1.0

  timeline_tile: ^2.0.0

  dio: ^4.0.6
  retrofit: '>=3.0.0 <4.0.0'
  curl_logger_dio_interceptor: ^0.0.3

  # flutter_auth_buttons: ^0.10.0
  auth_buttons: ^3.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  flutter_launcher_icons: ^0.11.0
  flutter_dotenv: ^5.0.2
  analyzer:

  phone_number: ^1.0.0
  connectivity_plus: ^3.0.2

dev_dependencies:
  # bloc_test: ^9.1.0

  flutter_test:
    sdk: flutter

  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner: ^2.3.3
  lint: ^2.0.1
  freezed:
  injectable_generator: ^2.1.3
  auto_route_generator:
  json_serializable: ^6.5.4
  mockito: ^5.3.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/injection.config.dart"

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/account_avatar_face_man_people_profile_user_icon.png
    - images/activite.jpeg
    - images/admin.jpg
    - images/childheadwithsmilingface.png
    - images/family.jpeg
    - images/family2.jpg
    - images/family_logo.png
    - images/fb-logo.png
    - images/garde_enfants.jpeg
    - images/400PngdpiLogo.png
    - images/logo.jpeg
    - images/recuperation_enfants.jpeg
    - images/location.png
    - resources/langs/
    - .env
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
