// Mocks generated by Mockito 5.2.0 from annotations
// in familytrusts/test/src/application/children_lookup/details/children_lookup_details_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:familytrusts/src/domain/auth/auth_failure.dart' as _i5;
import 'package:familytrusts/src/domain/auth/user_info.dart' as _i8;
import 'package:familytrusts/src/domain/children_lookup/children_lookup.dart'
    as _i12;
import 'package:familytrusts/src/domain/children_lookup/children_lookup_failure.dart'
    as _i11;
import 'package:familytrusts/src/domain/children_lookup/children_lookup_history.dart'
    as _i13;
import 'package:familytrusts/src/domain/invitation/invitation.dart' as _i19;
import 'package:familytrusts/src/domain/invitation/invitation_failure.dart'
    as _i18;
import 'package:familytrusts/src/domain/notification/event.dart' as _i17;
import 'package:familytrusts/src/domain/notification/event_failure.dart'
    as _i16;
import 'package:familytrusts/src/domain/notification/notifications_failure.dart'
    as _i20;
import 'package:familytrusts/src/domain/planning/planning.dart' as _i15;
import 'package:familytrusts/src/domain/planning/planning_failure.dart' as _i14;
import 'package:familytrusts/src/domain/user/user.dart' as _i10;
import 'package:familytrusts/src/domain/user/user_failure.dart' as _i9;
import 'package:familytrusts/src/domain/user/value_objects.dart' as _i6;
import 'package:firebase_auth/firebase_auth.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

import 'children_lookup_details_bloc_test.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeOption_0<A> extends _i1.Fake implements _i2.Option<A> {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [MockAuthFacade].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockAuthFacade extends _i1.Mock implements _i3.MockAuthFacade {
  MockMockAuthFacade() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Option<String> getSignedInUserId() =>
      (super.noSuchMethod(Invocation.method(#getSignedInUserId, []),
          returnValue: _FakeOption_0<String>()) as _i2.Option<String>);
  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, String>> registerWithEmailAndPassword(
          {_i6.EmailAddress? emailAddress, _i6.Password? password}) =>
      (super.noSuchMethod(
              Invocation.method(#registerWithEmailAndPassword, [],
                  {#emailAddress: emailAddress, #password: password}),
              returnValue: Future<_i2.Either<_i5.AuthFailure, String>>.value(
                  _FakeEither_1<_i5.AuthFailure, String>()))
          as _i4.Future<_i2.Either<_i5.AuthFailure, String>>);
  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, String>> signInWithEmailAndPassword(
          {_i6.EmailAddress? emailAddress, _i6.Password? password}) =>
      (super.noSuchMethod(
              Invocation.method(#signInWithEmailAndPassword, [],
                  {#emailAddress: emailAddress, #password: password}),
              returnValue: Future<_i2.Either<_i5.AuthFailure, String>>.value(
                  _FakeEither_1<_i5.AuthFailure, String>()))
          as _i4.Future<_i2.Either<_i5.AuthFailure, String>>);
  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, String>> signInWithGoogle() =>
      (super.noSuchMethod(Invocation.method(#signInWithGoogle, []),
              returnValue: Future<_i2.Either<_i5.AuthFailure, String>>.value(
                  _FakeEither_1<_i5.AuthFailure, String>()))
          as _i4.Future<_i2.Either<_i5.AuthFailure, String>>);
  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, String>> signInWithFacebook() =>
      (super.noSuchMethod(Invocation.method(#signInWithFacebook, []),
              returnValue: Future<_i2.Either<_i5.AuthFailure, String>>.value(
                  _FakeEither_1<_i5.AuthFailure, String>()))
          as _i4.Future<_i2.Either<_i5.AuthFailure, String>>);
  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(Invocation.method(#signOut, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i2.Option<_i7.User> getSignedInUser() =>
      (super.noSuchMethod(Invocation.method(#getSignedInUser, []),
          returnValue: _FakeOption_0<_i7.User>()) as _i2.Option<_i7.User>);
  @override
  _i4.Future<_i2.Option<_i8.MyUserInfo>> getSignedUserInfo() =>
      (super.noSuchMethod(Invocation.method(#getSignedUserInfo, []),
              returnValue: Future<_i2.Option<_i8.MyUserInfo>>.value(
                  _FakeOption_0<_i8.MyUserInfo>()))
          as _i4.Future<_i2.Option<_i8.MyUserInfo>>);
  @override
  _i4.Future<String> getToken() =>
      (super.noSuchMethod(Invocation.method(#getToken, []),
          returnValue: Future<String>.value('')) as _i4.Future<String>);
}

/// A class which mocks [MockUserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockUserRepository extends _i1.Mock
    implements _i3.MockUserRepository {
  MockMockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i9.UserFailure, _i2.Unit>> saveToken(
          String? userId, String? token) =>
      (super.noSuchMethod(Invocation.method(#saveToken, [userId, token]),
              returnValue: Future<_i2.Either<_i9.UserFailure, _i2.Unit>>.value(
                  _FakeEither_1<_i9.UserFailure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i9.UserFailure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i9.UserFailure, _i2.Unit>> create(_i10.User? user,
          {String? pickedFilePath}) =>
      (super.noSuchMethod(
          Invocation.method(#create, [user], {#pickedFilePath: pickedFilePath}),
          returnValue: Future<_i2.Either<_i9.UserFailure, _i2.Unit>>.value(
              _FakeEither_1<_i9.UserFailure, _i2.Unit>())) as _i4
          .Future<_i2.Either<_i9.UserFailure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i9.UserFailure, _i2.Unit>> update(_i10.User? user,
          {String? pickedFilePath}) =>
      (super.noSuchMethod(
          Invocation.method(#update, [user], {#pickedFilePath: pickedFilePath}),
          returnValue: Future<_i2.Either<_i9.UserFailure, _i2.Unit>>.value(
              _FakeEither_1<_i9.UserFailure, _i2.Unit>())) as _i4
          .Future<_i2.Either<_i9.UserFailure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i9.UserFailure, _i10.User>> getUser(String? id) =>
      (super.noSuchMethod(Invocation.method(#getUser, [id]),
              returnValue: Future<_i2.Either<_i9.UserFailure, _i10.User>>.value(
                  _FakeEither_1<_i9.UserFailure, _i10.User>()))
          as _i4.Future<_i2.Either<_i9.UserFailure, _i10.User>>);
}

/// A class which mocks [MockChildrenLookupRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockChildrenLookupRepository extends _i1.Mock
    implements _i3.MockChildrenLookupRepository {
  MockMockChildrenLookupRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i2.Either<_i11.ChildrenLookupFailure, _i12.ChildrenLookup>>>
      getChildrenLookupsByFamilyId({String? familyId}) => (super.noSuchMethod(
              Invocation.method(
                  #getChildrenLookupsByFamilyId, [], {#familyId: familyId}),
              returnValue:
                  Stream<List<_i2.Either<_i11.ChildrenLookupFailure, _i12.ChildrenLookup>>>.empty())
          as _i4.Stream<
              List<_i2.Either<_i11.ChildrenLookupFailure, _i12.ChildrenLookup>>>);
  @override
  _i4.Stream<List<_i2.Either<_i11.ChildrenLookupFailure, _i12.ChildrenLookup>>>
      getChildrenLookupsByTrustedId({String? trustedUserId}) => (super.noSuchMethod(
              Invocation.method(#getChildrenLookupsByTrustedId, [],
                  {#trustedUserId: trustedUserId}),
              returnValue:
                  Stream<List<_i2.Either<_i11.ChildrenLookupFailure, _i12.ChildrenLookup>>>.empty())
          as _i4.Stream<
              List<_i2.Either<_i11.ChildrenLookupFailure, _i12.ChildrenLookup>>>);
  @override
  _i4.Stream<List<_i2.Either<_i11.ChildrenLookupFailure, _i13.ChildrenLookupHistory>>>
      getChildrenLookupHistories({String? childrenLookupId}) => (super.noSuchMethod(
              Invocation.method(#getChildrenLookupHistories, [],
                  {#childrenLookupId: childrenLookupId}),
              returnValue:
                  Stream<List<_i2.Either<_i11.ChildrenLookupFailure, _i13.ChildrenLookupHistory>>>.empty())
          as _i4.Stream<
              List<_i2.Either<_i11.ChildrenLookupFailure, _i13.ChildrenLookupHistory>>>);
  @override
  _i4.Future<_i2.Either<_i11.ChildrenLookupFailure, _i2.Unit>>
      addChildrenLookupHistory(
              {String? childrenLookupId,
              _i13.ChildrenLookupHistory? childrenLookupHistory}) =>
          (super.noSuchMethod(
              Invocation.method(#addChildrenLookupHistory, [], {
                #childrenLookupId: childrenLookupId,
                #childrenLookupHistory: childrenLookupHistory
              }),
              returnValue: Future<
                      _i2.Either<_i11.ChildrenLookupFailure, _i2.Unit>>.value(
                  _FakeEither_1<_i11.ChildrenLookupFailure, _i2.Unit>())) as _i4
              .Future<_i2.Either<_i11.ChildrenLookupFailure, _i2.Unit>>);
  @override
  _i4.Future<
      _i2.Either<_i11.ChildrenLookupFailure, _i2.Unit>> addUpdateChildrenLookup(
          {_i12.ChildrenLookup? childrenLookup}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #addUpdateChildrenLookup, [], {#childrenLookup: childrenLookup}),
              returnValue:
                  Future<_i2.Either<_i11.ChildrenLookupFailure, _i2.Unit>>.value(
                      _FakeEither_1<_i11.ChildrenLookupFailure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i11.ChildrenLookupFailure, _i2.Unit>>);
  @override
  _i4.Stream<_i2.Either<_i11.ChildrenLookupFailure, _i12.ChildrenLookup>>
      watchChildrenLookup({String? childrenLookupId}) => (super.noSuchMethod(
          Invocation.method(
              #watchChildrenLookup, [], {#childrenLookupId: childrenLookupId}),
          returnValue: Stream<
              _i2.Either<_i11.ChildrenLookupFailure, _i12.ChildrenLookup>>.empty()) as _i4
          .Stream<_i2.Either<_i11.ChildrenLookupFailure, _i12.ChildrenLookup>>);
  @override
  _i4.Stream<_i2.Either<_i14.PlanningFailure, _i15.Planning>> getPlanning(
          {String? userId}) =>
      (super.noSuchMethod(
              Invocation.method(#getPlanning, [], {#userId: userId}),
              returnValue: Stream<
                  _i2.Either<_i14.PlanningFailure, _i15.Planning>>.empty())
          as _i4.Stream<_i2.Either<_i14.PlanningFailure, _i15.Planning>>);
}

/// A class which mocks [MockNotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockNotificationRepository extends _i1.Mock
    implements _i3.MockNotificationRepository {
  MockMockNotificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i2.Either<_i16.EventFailure, _i17.Event>>> getEvents(
          String? userId) =>
      (super.noSuchMethod(Invocation.method(#getEvents, [userId]),
              returnValue: Stream<
                  List<_i2.Either<_i16.EventFailure, _i17.Event>>>.empty())
          as _i4.Stream<List<_i2.Either<_i16.EventFailure, _i17.Event>>>);
  @override
  _i4.Stream<List<_i2.Either<_i18.InvitationFailure, _i19.Invitation>>>
      getInvitations(String? userId) => (super.noSuchMethod(
          Invocation.method(#getInvitations, [userId]),
          returnValue: Stream<
              List<
                  _i2.Either<_i18.InvitationFailure,
                      _i19.Invitation>>>.empty()) as _i4
          .Stream<List<_i2.Either<_i18.InvitationFailure, _i19.Invitation>>>);
  @override
  _i4.Stream<_i2.Either<_i20.NotificationsFailure, int>> getUnRedCount(
          String? userId) =>
      (super.noSuchMethod(Invocation.method(#getUnRedCount, [userId]),
              returnValue:
                  Stream<_i2.Either<_i20.NotificationsFailure, int>>.empty())
          as _i4.Stream<_i2.Either<_i20.NotificationsFailure, int>>);
  @override
  _i4.Future<_i2.Either<_i20.NotificationsFailure, _i2.Unit>> createEvent(
          String? userId, _i17.Event? event) =>
      (super.noSuchMethod(Invocation.method(#createEvent, [userId, event]),
              returnValue:
                  Future<_i2.Either<_i20.NotificationsFailure, _i2.Unit>>.value(
                      _FakeEither_1<_i20.NotificationsFailure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i20.NotificationsFailure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i20.NotificationsFailure, _i2.Unit>> updateEvent(
          String? userId, _i17.Event? event) =>
      (super.noSuchMethod(Invocation.method(#updateEvent, [userId, event]),
              returnValue:
                  Future<_i2.Either<_i20.NotificationsFailure, _i2.Unit>>.value(
                      _FakeEither_1<_i20.NotificationsFailure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i20.NotificationsFailure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i20.NotificationsFailure, _i2.Unit>> deleteEvent(
          String? userId, _i17.Event? event) =>
      (super.noSuchMethod(Invocation.method(#deleteEvent, [userId, event]),
              returnValue:
                  Future<_i2.Either<_i20.NotificationsFailure, _i2.Unit>>.value(
                      _FakeEither_1<_i20.NotificationsFailure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i20.NotificationsFailure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i20.NotificationsFailure, _i2.Unit>> createInvitation(
          _i19.Invitation? invitation) =>
      (super.noSuchMethod(Invocation.method(#createInvitation, [invitation]),
              returnValue:
                  Future<_i2.Either<_i20.NotificationsFailure, _i2.Unit>>.value(
                      _FakeEither_1<_i20.NotificationsFailure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i20.NotificationsFailure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i20.NotificationsFailure, _i2.Unit>> deleteInvitation(
          {_i10.User? from, _i10.User? to}) =>
      (super.noSuchMethod(
              Invocation.method(#deleteInvitation, [], {#from: from, #to: to}),
              returnValue:
                  Future<_i2.Either<_i20.NotificationsFailure, _i2.Unit>>.value(
                      _FakeEither_1<_i20.NotificationsFailure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i20.NotificationsFailure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i20.NotificationsFailure, _i2.Unit>>
      createEventForChildrenLookup(
              _i12.ChildrenLookup? childrenLookup, _i17.Event? event) =>
          (super.noSuchMethod(
              Invocation.method(
                  #createEventForChildrenLookup, [childrenLookup, event]),
              returnValue:
                  Future<_i2.Either<_i20.NotificationsFailure, _i2.Unit>>.value(
                      _FakeEither_1<_i20.NotificationsFailure, _i2.Unit>())) as _i4
              .Future<_i2.Either<_i20.NotificationsFailure, _i2.Unit>>);
}
